export {Home} from "./Home/Home"
export {Access} from "./Access/Access"
export {Recipes} from "./Recipes/Recipes"
export {MyProfile} from "./MyProfile/MyProfile"
export {RecipeDetail} from "./RecipeDetail/RecipeDetail"
export {RecipeEdit} from "./RecipeEdit/RecipeEdit"
export {RecipeAdd} from "./RecipeAdd/RecipeAdd"
export {MyFavorites} from "./MyFavorites/MyFavorites"
export {Config} from "./Config/Config"
// export {ProjectDetail} from "./ProjectDetail/ProjectDetail"